# Default setting that are applied no matter what profile is used
# If a profile defines the same property, then the value from the profile is used
# That means that these have the lowest priority and properties defined in profiles
# have higher priorities
jaeger:
  protocol: HTTP
  sender: http://jaeger-collector-demo-cloud-native.192.168.42.13.nip.io/api/traces
  port: 0
---
spring:
  jpa:
    hibernate.ddl-auto: update
    show_sql: false
---
# Local profile used for labtop demo
spring.profiles: local
spring:
  datasource:
    url: jdbc:h2:mem:DEMO
    username: sa
    password:
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
    console.path: /h2-console
---
# Profile used when app deployed on Cloudfoundry
spring.profiles: cloudfoundry
spring:
  datasource:
    url: ${vcap.services.cleardb.credentials.jdbcUrl}
    username: ${vcap.services.cleardb.credentials.username}
    password: ${vcap.services.cleardb.credentials.password}
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
---
# Profile used when app deployed on OpenShift
spring.profiles: openshift
spring:
  datasource:
    url: jdbc:mysql://${db.host}:3306/${db.name}
    username: ${db.user}
    password: ${db.password}
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

jaeger:
  sender: http://jaeger-collector-jaeger.ocp.spring-boot.osepool.centralci.eng.rdu2.redhat.com/api/traces
